version: "3"

services:

  influx:
    image: influxdb
    ports:
      - '8083:8083'
    labels:
      # These register the service with the dockerflow proxy
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.servicePath=/_influx
      - com.df.port=8083
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - diagnostics
      - proxy
    deploy:
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    labels:
      # These register the service with the dockerflow proxy
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.servicePath=/_grafana
      - com.df.port=3000
    volumes:
      - grafana:/var/lib/grafana
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - diagnostics
      - proxy

  telegraf:
    image: telegraf
    deploy:
      mode: global
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/anurse/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - diagnostics


volumes:
  grafana:
    external: true

  influxdb:
    external: true

networks:
  diagnostics:
    external: true

  proxy:
    external: true
