version: '3.3'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT
      - Authentication__Tenant
      - Authentication__ClientId
      - ConnectionStrings__DefaultConnection

  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT
      - Authentication__Tenant
      - Authentication__ClientId
      - Authentication__ClientSecret
    ports:
      - "80:80"
