version: '3'

services:
  backend:
    environment:
      - "ConnectionStrings__DefaultConnection=${ConferencePlanner_SqlConnectionString}"
      - ASPNETCORE_ENVIRONMENT

  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT
    ports:
      - "80:80"
