version: '3.3'

services:
  backend:
    image: anurseconferenceplanner.azurecr.io/backend
    expose:
      - "80"
    build:
      context: ./src/ConferencePlanner.BackEnd
      dockerfile: Dockerfile
      args:
        source: './bin/${BUILDCONFIGURATION:-Debug}/netcoreapp2.0/publish'
    networks:
      - backend
      - frontend

  frontend:
    image: anurseconferenceplanner.azurecr.io/frontend
    expose:
      - "80"
    environment:
      ServiceUrl: 'http://backend'
    build:
      context: ./src/ConferencePlanner.FrontEnd
      dockerfile: Dockerfile
      args:
        source: './bin/${BUILDCONFIGURATION:-Debug}/netcoreapp2.0/publish'
    networks:
      - frontend

networks:
    frontend:
    backend:
